### PR TITLE
Fix embedded image width

### LINKED ISSUE #22: Media should fill the container the best it can
Media in tweets doesn't always fill the container, and it looks like a bug. Occasionally the media isn't centered either, which makes it worse.

screen shot 2016-05-10 at 8 17 30 pm

screen shot 2016-05-10 at 8 20 50 pm

### PR DESCRIPTION
**Pull request by paulmolluzzo**
Fixes #22.

Compare the below with the images in the original issue:

screen shot 2016-05-10 at 8 52 06 pm

screen shot 2016-05-10 at 8 52 13 pm

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hmm, not sure about this. The reason they're not filling the container is that the image isn't large enough. Do we really want to enlarge images and cause them to be pixelated/blurry? Regardless, we should definitely fix the centering bug.

**Comment by paulmolluzzo** [comment]
> Hmm, not sure about this. The reason they're not filling the container is that the image isn't large enough. Do we really want to enlarge images and cause them to be pixelated/blurry?

It's really not super off, at least the images I found. IMHO the huge border is worse than some pixelation, but that's because they're using `display: flex;` (I think that's why) and getting around that means redoing the layout.

A simpler solution is to put a `max-width` on the container like we did in `refined-twitter` so we don't have these monstrously wide tweets.

> Regardless, we should definitely fix the centering bug.

I can add that in now.

**Comment by paulmolluzzo** [comment]
@sindresorhus the centering is fixed but I haven't taken out the full width. If you notice a lot of pixelation, just comment here and I'll take that out and leave only the centering fix.

**Comment by sindresorhus** [comment]
> A simpler solution is to put a max-width on the container like we did in refined-twitter so we don't have these monstrously wide tweets.

That would look weird though. Since this is an app you expect the content to fill the container or the container to be limited. Maybe it would make more sense to limit the width of the window? The official Twitter app does that:

(max width) 

screen shot 2016-05-12 at 12 58 52

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by paulmolluzzo** [comment]
> Maybe it would make more sense to limit the width of the window? The official Twitter app does that.

Yeah, that could work too. But we'd lose full screen support I think, if that matters.

**Comment by sindresorhus** [comment]
We could still allow fullscreen. Just apply the same width fix as refined-twitter.

**Comment by paulmolluzzo** [comment]
Ok, I like it. It doesn't look good super wide IMO. The layout is too fluid and all the avatars get huge. There needs to be some limitation in place.

**Pull request merged**
